{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="hidden" name="{$attribute_base}_sum_{$attribute.id}" size="12" value=""/>{section show=$attribute.has_http_value}{$attribute.value}{section-else}{$attribute.content.sum|l10n(number)}{/section}

<script type="text/javascript" src="http://jqueryjs.googlecode.com/files/jquery-1.2.6.pack.js" ></script>
<script type="text/javascript">
var count = function(id){ldelim}
    var res = 0;
    var find = /({$attribute.content.suffix}$)/;
    $('#editform input[type="text"]').each(function(){ldelim}
        var str = $(this).attr('id');
        if( find.test(str) ){ldelim} res += parseInt($(this).val()); {rdelim}
    });
    $('#'+id).val(res);
{rdelim}
$('#editform').submit(function(){ldelim} count('ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}'); {rdelim});
</script>
{/default}