{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Attributes identifier suffix'|i18n( 'design/standard/class/datatype' )}:</label>
    <input type="text" name="ContentClass_ezjssum_integer_suffix_{$class_attribute.id}" value="{$class_attribute.content.suffix|wash()}" size="25" maxlength="20" />
</div>